twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
      docking:
        topic   : cmd_vel_docking
        timeout : 0.5
        priority: 20
      joystick:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 100
      